name: servio_mobile

packages:
  - apps/*
  - packages/*

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages.
  
  test:
    run: melos exec --dir-exists="test" -- "flutter test"
    description: Run `flutter test` in all packages.

  build:runner:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run `build_runner build` in all packages that depend on it.
